# Publish all joint states -----------------------------------
$(arg prefix)joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

$(arg prefix)joint_1_position_controller:
    joint: $(arg prefix)joint_1
    pid:
        p: 3000.0
        i: 0.0
        d: 2.0
    type: effort_controllers/JointPositionController

$(arg prefix)joint_2_position_controller:
    joint: $(arg prefix)joint_2
    pid:
        p: 50000.0
        i: 0.0
        d: 0.0
    type: effort_controllers/JointPositionController

$(arg prefix)joint_3_position_controller:
    joint: $(arg prefix)joint_3
    pid:
        p: 3000.0
        i: 0.0
        d: 0.0
    type: effort_controllers/JointPositionController

$(arg prefix)joint_4_position_controller:
    joint: $(arg prefix)joint_4
    pid:
        p: 50000.0
        i: 0.0
        d: 0.0
    type: effort_controllers/JointPositionController

$(arg prefix)joint_5_position_controller:
    joint: $(arg prefix)joint_5
    pid:
        p: 750.0
        i: 0.0
        d: 0.2
    type: effort_controllers/JointPositionController

$(arg prefix)joint_6_position_controller:
    joint: $(arg prefix)joint_6
    pid:
        p: 5000.0
        i: 0.0
        d: 1.0
    type: effort_controllers/JointPositionController

$(arg prefix)joint_7_position_controller:
    joint: $(arg prefix)joint_7
    pid:
        p: 100.0
        i: 0.0
        d: 0.0
    type: effort_controllers/JointPositionController
